name = "CountriesBorders"
uuid = "ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.2.1"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = "PlotlyBase"

[compat]
GeoInterface = "1"
GeoTables = "1"
Meshes = "0.28.1, 0.44"
PlotlyBase = "0.8.19"
Tables = "1"
julia = "1.9"
